// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var endpoint = "http://localhost:3000";

function fetch$1(api) {
  return fetch("" + (String(endpoint) + ("" + (String(api) + "")))).then((function (prim) {
                  return prim.text();
                })).then((function (result) {
                return Promise.resolve(JSON.parse(result));
              }));
}

var client = {
  user: {
    me: (function (param) {
        return fetch$1("/users/me");
      })
  },
  ticket: {
    get: (function (ticketId) {
        return fetch$1("/tickets/" + (String(ticketId) + ""));
      })
  },
  comment: {
    list: (function (ticketId) {
        return fetch$1("/tickets/" + (String(ticketId) + "/comments"));
      })
  },
  page: {
    list: (function (ticketId) {
        return fetch$1("/tickets/" + (String(ticketId) + "/pages"));
      })
  },
  project: {
    listRecent: (function (param) {
        return fetch$1("/projects/recent");
      })
  }
};

exports.endpoint = endpoint;
exports.fetch = fetch$1;
exports.client = client;
/* No side effect */
