service: pyxis

plugins:
  - serverless-plugin-tracing
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  tracing: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - src/**
    - node_modules/**

functions:
  hello:
    handler: src/functions/echo.handler

  listRecentProjects:
    handler: src/functions/Project.bs.listRecent
    events:
      - http:
          path: /projects/recent
          method: get
  getProject:
    handler: src/functions/Project.bs.get
    events:
      - http:
          path: /projects/{projectId}
          method: get

  getTicket:
    handler: src/functions/Ticket.bs.get
    events:
      - http:
          path: /tickets/{ticketId}
          method: get

  listPages:
    handler: src/functions/Page.bs.get
    events:
      - http:
          path: /tickets/{ticketId}/pages
          method: get

  createComment:
    handler: src/functions/Comment.bs.create
    events:
      - http:
          path: /comments
          method: post
  listComments:
    handler: src/functions/Comment.bs.list
    events:
      - http:
          path: /tickets/{ticketId}/comments
          method: get

  getMe:
    handler: src/functions/User.bs.getMe
    events:
      - http:
          path: /users/me
          method: get
          cors: true

resources:
  Resources:
    TicketTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: entities
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sort
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: sort
            AttributeType: S
          - AttributeName: owned_by
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: owners
            KeySchema:
              - AttributeName: owned_by
                KeyType: HASH
              - AttributeName: id
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
              - title
              - belongs_to
              - comment
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: entities
            sources: [ "./migrations/entities.json" ]

