service: pyxis

plugins:
  - serverless-plugin-tracing
  - serverless-dynamodb-local
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  tracing: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - src/**
    - node_modules/**

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: users
            sources: [ "./migrations/users.json" ]
          - table: tickets
            sources: [ "./migrations/tickets.json" ]

functions:
  hello:
    handler: src/functions/echo.handler

  listRecentProject:
    handler: src/functions/project.listRecent
    events:
      - http:
          path: /projects/recent
          method: get
  getProject:
    handler: src/functions/project.get
    events:
      - http:
          path: /projects/{id}
          method: get

  getTicket:
    handler: src/functions/ticket.get
    events:
      - http:
          path: /projects/{projectId}/tickets/{ticketId}
          method: get

  listComment:
    handler: src/functions/comment.list
    events:
      - http:
          path: /projects/{projectId}/tickets/{ticketId}/comments/
          method: get

  getMe:
    handler: src/functions/user.getMe
    events:
      - http:
          path: /users/me
          method: get
          cors: true

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: users
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sort
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: sort
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TicketTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: tickets
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sort
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: sort
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
